apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: order-taskrun
spec:
  serviceAccountName: front-svc-acc 
  taskRef:
    name: order
  params:
  - name: IMAGE
    value: "walaafahad/orders"
  resources:
    inputs:
    - name: order-resource
      resourceRef:
        name: order-resource 
