apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: catlogdb-pipeline
spec:
  resources:
    - name: catalogue-resource
      type: git
  tasks:
    - name: build
      taskRef:
        name: catalogue-db-build
      resources:
        inputs: 
        - name: catalogue-resource
          resource: catalogue-resource
    - name: catalog-db-deploy-kubectl
      runAfter: ["build"]
      taskRef:
        name: catalog-db-deploy-kubectl
      resources:
        inputs:
        - name: catalogue-resource
          resource: catalogue-resource

