apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: catalogue-db-build-runner
spec:
  serviceAccountName: front-svc-acc
  taskRef:
    name: catalogue-db
  params:
  - name: IMAGE
    value: "walaafahad/catalogue-db"
  resources:
    inputs:
    - name: catalogue-resource
      resourceRef:
        name: catalogue-resource
