
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: queue-master-src
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/walaafahad1994/level3-project