apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: catalogue-run-images
spec:
  serviceAccountName: front-svc-acc
  taskRef:
    name: catalogue
  resources:
    inputs:
    - name: catalogue-resource
      resourceRef:
        name: catalogue-resource
  params:
    - name: IMAGE
      value: "walaafahad/catalogue"