apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: carts-deploy-kubectl
  serviceAccountName: cart-svc-acc
spec:
  params:
    - name: pathToYamlFile
      type: string
      description: The path to the yaml file to deploy within the git source
      default: $(resources.inputs.carts-resource.path)/carts/tasks/cart-svc.yaml
    - name: pathToDbYamlFile
      type: string
      default:  $(resources.inputs.carts-resource.path)/carts/tasks/cart-db-svc.yaml
    - name: namespace
      default: test
  resources:
    inputs:
      - name: carts-resource
        type: git
  steps:
   - name: run-kubectl
     image: lachlanevenson/k8s-kubectl
     command: ["kubectl"]
     args:
       - "apply"
       - "-f"
       - "$(params.pathToDbYamlFile)"
       - "-f"
       - "$(params.pathToYamlFile)"
       - "-n"
       - "$(params.namespace)"
