apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: user-taskrun
spec:
  serviceAccountName: front-svc-acc 
  taskRef:
    name: user
  params:
  - name: IMAGE
    value: "walaafahad/users"
  resources:
    inputs:
    - name: user-resource
      resourceRef:
        name: user-resource 
