apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ship-deploy-kubectl
  serviceAccountName: ship-svc-acc
spec:
  params:
    - name: pathToYamlFile
      type: string
      description: The path to the yaml file to deploy within the git source
      default: $(resources.inputs.ship-resource.path)/shipping/tasks/ship-svc-dep.yaml
    - name: pathToDbYamlFile
      type: string
      default:  $(resources.inputs.ship-resource.path)/shipping/tasks/orderdb-dep.yaml
    - name: namespace
      default: test
  resources:
    inputs:
      - name: ship-resource
        type: git
  steps:
   - name: run-kubectl
     image: lachlanevenson/k8s-kubectl
     command: ["kubectl"]
     args:
       - "apply"
       - "-f"
       - "$(params.pathToDbYamlFile)"
       - "-f"
       - "$(params.pathToYamlFile)"
       - "-n"
       - "$(params.namespace)"
